version: '3.6'

services:
  db:
    image: postgres:15.1
    container_name: dev-db
    ports:
      - "7368:5432"
    volumes:
      - ./infrastructure/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=procd
      - POSTGRES_PASSWORD=procd_password
    restart: "no"

  keycloak:
    build:
      context: ./infrastructure/keycloak
    container_name: procd-keycloak
    environment:
      - KEYCLOAK_ADMIN=procd
      - KEYCLOAK_ADMIN_PASSWORD=procd
      - KC_DB_USERNAME=procd
      - KC_DB_PASSWORD=procd_password
      - KC_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KC_DB_DATABASE=procd
      - KC_DB=postgres
      - KC_HOSTNAME_STRICT=false
      - KC_EDGE=proxy
    ports:
      - "7367:8080"
    depends_on:
      - db
    restart: "no"