object Dependencies {
    const val BEN_MANES_VERSION = "0.49.0"
    const val LANGUAGE_VERSION = "1.9"
    const val KOTLIN_VERSION = "1.9.10"
    const val JVM_TARGET = "17"
    const val JIB = "3.4.0"

    private const val KTOR = "2.3.5"
    private const val KOTLIN_SERIALIZATION = "1.6.0"
    private const val KOTLINX = "1.7.3"
    private const val VERTX = "4.4.6"
    private const val LOGBACK = "1.4.11"
    private const val JUNIT = "5.10.0"
    private const val KEYCLOAK = "24.0.3"
    private const val TESTCONTAINERS = "1.19.1"
    private const val TESTCONTAINERS_KEYCLOAK = "3.0.0"
    private const val KOIN = "3.5.0"
    private const val KOIN_KTOR = "3.5.1"
    private const val FLYWAY = "9.22.3"
    private const val HIBERNATE = "8.0.1.Final"
    private const val JAKARTA = "5.0.0-M1"
    private const val EXPRESSLY = "5.0.0"
    private const val JAKSON = "2.15.3"
    private const val JBCRYPT = "0.4"
    private const val POSTGRES = "42.6.0"
    private const val SCRAM = "2.1"
    private const val REFLECTIONS = "0.10.2"
    private const val XSTREAM = "1.4.20"
    private const val MICROMETER = "1.11.5"
    private const val FAKER = "1.15.0"
    private const val NETTY = "4.1.100.Final"
    private const val KOTLIN_LOGGING = "3.0.5"

    fun kotlin(module: String) = "org.jetbrains.kotlin:kotlin-${module}:$KOTLIN_VERSION"
    fun kotlinCoroutines(module: String) =
        "org.jetbrains.kotlinx:kotlinx-coroutines-${module}:$KOTLINX"

    fun kotlinSerialization(module: String) =
        "org.jetbrains.kotlinx:kotlinx-serialization-${module}:$KOTLIN_SERIALIZATION"

    fun postgres() = "org.postgresql:postgresql:$POSTGRES"
    fun flyway() = "org.flywaydb:flyway-core:$FLYWAY"
    fun jbcrypt() = "org.mindrot:jbcrypt:$JBCRYPT"
    fun vertx(module: String) = "io.vertx:vertx-${module}:$VERTX"
    fun ktor(module: String) = "io.ktor:ktor-${module}-jvm:$KTOR"
    fun koin(module: String) = "io.insert-koin:koin-${module}:$KOIN"
    fun koinKtor() = "io.insert-koin:koin-ktor:$KOIN_KTOR"
    fun logback(module: String) = "ch.qos.logback:logback-${module}:$LOGBACK"
    fun testContainers(module: String) = "org.testcontainers:${module}:$TESTCONTAINERS"
    fun junit(module: String) = "org.junit.jupiter:junit-${module}:$JUNIT"
    fun jakarta(module: String) = "org.glassfish:jakarta.${module}:$JAKARTA"
    fun expressly() = "org.glassfish.expressly:expressly:$EXPRESSLY"
    fun hibernateValidator() = "org.hibernate.validator:hibernate-validator:$HIBERNATE"
    fun jackson(packageName: String, module: String) =
        "com.fasterxml.jackson.${packageName}:jackson-${module}:$JAKSON"

    fun jackson() = "com.fasterxml.jackson.module:jackson-module-kotlin:$JAKSON"
    fun keycloak(module: String) = "org.keycloak:keycloak-${module}:$KEYCLOAK"
    fun scram(module: String) = "com.ongres.scram:${module}:$SCRAM"
    fun reflections() = "org.reflections:reflections:$REFLECTIONS"
    fun xstream() = "com.thoughtworks.xstream:xstream:$XSTREAM"
    fun micrometer() = "io.micrometer:micrometer-registry-prometheus:$MICROMETER"
    fun faker() = "io.github.serpro69:kotlin-faker:$FAKER"
    fun netty(module: String) = "io.netty:netty-$module:$NETTY"
    fun kotlinLogging() = "io.github.microutils:kotlin-logging-jvm:${KOTLIN_LOGGING}"
    fun keycloakTestContainers() = "com.github.dasniko:testcontainers-keycloak:$TESTCONTAINERS_KEYCLOAK"
}
